// auth
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

// connected users
export const ADD_CONNECTED_USERS = "ADD_CONNECTED_USERS";
export const UPDATE_CONNECTED_USERS = "UPDATE_CONNECTED_USERS";
export const REMOVE_CONNECTED_USERS = "REMOVE_CONNECTED_USERS";
export const CHANGE_SELECTED_USER = "CHANGE_SELECTED_USER";

// message
export const ADD_MESSAGE = "ADD_MESSAGE";
export const UPDATE_SUCCESSFULLY_SENT_MESSAGE =
  "UPDATE_SUCCESSFULLY_SENT_MESSAGE";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const TOGGLE_FETCHING_MESSAGE = "TOGGLE_FETCHING_MESSAGE";

// settings
export const TOGGLE_SCREEN_SPLIT = "TOGGLE_SCREEN_SPLIT";

// search
export const ADD_SEARCH_USERS_LIST = "ADD_SEARCH_USERS_LIST";
export const REMOVE_SEARCH_USERS_LIST = "REMOVE_SEARCH_USERS_LIST";
export const UPDATE_SEARCHING_USERS = "UPDATE_SEARCHING_USERS";
